name: building_damage_assessment
channels:
  - pytorch
  - defaults
dependencies:
  - blas
  - ca-certificates
  - certifi
  - cudatoolkit
  - freetype
  - intel-openmp
  - jpeg
  - libpng
  - libtiff
  - libuv
  - libwebp
  - lz4-c
  - mkl
  - ninja
  - ninja-base
  - openssl
  - pip
  - python=3.8.13
  - pytorch
  - setuptools
  - sqlite
  - tk
  - torchvision=0.10.0=py38_cu102
  - typing_extensions
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - vc
    - wincertstore
    - albumentations==1.1.0
    - argparse==1.4.0
    - atomicwrites==1.4.0
    - attrs==21.4.0
    - colorama==0.4.4
    - configparser==5.2.0
    - contextlib2==21.6.0
    - datetime==4.4
    - execnet==1.9.0
    - imageio==2.19.1
    - iniconfig==1.1.1
    - joblib==1.1.0
    - mock==4.0.3
    - networkx==2.8
    - numpy==1.22.3
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.5.64
    - packaging==21.3
    - path==16.4.0
    - path-py==12.5.0
    - pillow==8.3.2
    - pluggy==1.0.0
    - py==1.11.0
    - pyparsing==3.0.9
    - pytest==7.1.2
    - pytest-shutil==1.7.0
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - qudida==0.0.4
    - scikit-image==0.19.2
    - scikit-learn==1.1.0
    - scipy==1.8.0
    - six==1.16.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2022.5.4
    - tomli==2.0.1
    - tqdm==4.64.0
    - ttach==0.0.3
    - zope-interface==5.4.0
#prefix: C:\ProgramData\Anaconda3\envs\building_damage_assessment
